# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Clean workspace
        run: |
          sudo rm -rf /home/ubuntu/frontend-runner/workspace/frontend_demo/frontend_demo || true
          sudo mkdir -p /home/ubuntu/frontend-runner/workspace/frontend_demo/frontend_demo
          sudo chown -R ubuntu:ubuntu /home/ubuntu/frontend-runner/workspace/frontend_demo
          sudo chmod -R 755 /home/ubuntu/frontend-runner/workspace/frontend_demo

      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

        env:
          CI: false  # This prevents npm from running in CI mode, which can skip optional dependencies

      - name: Verify react-scripts installation
        run: |
          if ! [ -x "$(command -v react-scripts)" ]; then
            echo "react-scripts is not installed. Installing it now..."
            npm install react-scripts --save
          fi

      - run: npm run build
